// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"Marketplace/internal/api"
	"Marketplace/internal/api/handler"
	"Marketplace/internal/config"
	"Marketplace/internal/db"
	"Marketplace/internal/repository"
	"Marketplace/internal/service"
	"Marketplace/internal/utils/jwt"
	_ "github.com/lib/pq"
)

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	if err != nil {
		return nil, err
	}
	companyRepository := repository.NewCompanyRepository(sqlxDB)
	influencerRepository := repository.NewInfluencerRepository(sqlxDB)
	codeRepository := repository.NewCodeRepository(sqlxDB)
	v := jwt.ProvideSecretKey()
	companyService := service.NewCompanyService(companyRepository, codeRepository, v)
	influencerService := service.NewInfluencerService(influencerRepository, v)
	companyHandler := handler.NewCompanyHandler(companyService)
	influencerHandler := handler.NewInfluencerHandler(influencerService)
	server := api.NewServer(companyHandler, influencerHandler)
	return server, nil
}
